defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:20.10

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm run test
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy
          command: npm publish
workflows:
  version: 2
  deploy:
    jobs:
      - test:
          context: npm
      - deploy:
          context: npm
          requires:
            - test
          filters:
            branches:
              only: master